services:
    db:
        image: mariadb:10.6
        environment:
            - MARIADB_ROOT_PASSWORD=my-secret-pw
        restart: always
        ports:
            - 3306:3306
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
            interval: 3s
            retries: 5
            start_period: 30s
        volumes:
            - db-data:/var/lib/mysql
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    rabbitmq:
        image: rabbitmq:3.9.11-management
        ports:
            - 5672:5672
            - 15672:15672

volumes:
    db-data: {}